data:
  path: "data/dic_range_bar_new.pickle"
  segments:
    - ["2022_02_07", "2026_04_01"]
   
backtest:
  alpha_name: "range_bar_001"
  gen_name: "1_2"
  lst_frequency: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  lst_fee: [0.175]
  cores: 30

system_log:
  enabled: false

compute_score:
  enabled: false
  num_neighbors: 4
  cores: 30

visualize:
  enabled: true
  output_dir: "outputs/html"
  chart_colors: ['#081d58', '#225ea8', '#41b6c4', '#7ed957', '#edf8b1']
  cores: 13

storage:
  enabled: true
  output_dir: "outputs/excel"
  cores: 13

upload:
  enabled: true
  target_folder_id: "117gtokgAHiGDRF4c-6vmiXz75i_M1XQu"
  cores: 13
  
log_link:
  sheet_path: "logs/drive_links.json"

notification:
  enabled: true

